export const CONSOLE_NAMES = [
  "Thomson MO5",
  "Nintendo eShop",
  "Windows Phone",
  "WonderSwan Color",
  "SteamVR",
  "Tapwave Zodiac",
  "Xbox Project Scarlett",
  "ColecoVision",
  "Exidy Sorcerer",
  "Linux",
  "PC (Microsoft Windows)",
  "PlayStation",
  "PlayStation 2",
  "PlayStation 3",
  "Super Nintendo Entertainment System (SNES)",
  "Amstrad CPC",
  "MSX",
  "iOS",
  "Apple II",
  "Neo Geo AES",
  "Commodore Plus/4",
  "PDP-10",
  "Sol-20",
  "Texas Instruments TI-99",
  "Philips Videopac G7000",
  "Acorn Electron",
  "Google Stadia",
  "Stadia",
  "Family Computer Disk System",
  "Neo Geo Pocket Color",
  "PlayStation VR",
  "Intellivision",
  "Neo Geo CD",
  "Commodore VIC-20",
  "PC-50X Family",
  "AY-3-8710",
  "AY-3-8605",
  "Odyssey",
  "Commodore PET",
  "AY-3-8606",
  "Bally Astrocade",
  "Xbox",
  "Xbox 360",
  "Daydream",
  "PlayStation 4",
  "PDP-8",
  "Apple IIGS",
  "FM Towns",
  "TRS-80",
  "PC Engine SuperGrafx",
  "Hyper Neo Geo 64",
  "DEC GT40",
  "HP 3000",
  "Nintendo 64",
  "Xbox Live Arcade",
  "PlayStation Network",
  "PlayStation Vita",
  "Virtual Console (Nintendo)",
  "MSX2",
  "WiiWare",
  "WonderSwan",
  "Atari 7800",
  "Atari Jaguar",
  "Atari 8-bit",
  "Atari 5200",
  "SwanCrystal",
  "Fairchild Channel F",
  "Nintendo PlayStation",
  "AY-3-8607",
  "PC-98",
  "Mac",
  "Commodore CDTV",
  "Commodore C64/128",
  "Android",
  "Sega Game Gear",
  "Virtual Boy",
  "SteamOS",
  "Nintendo DSi",
  "3DO Interactive Multiplayer",
  "Neo Geo Pocket",
  "Arcade",
  "Mobile",
  "Super Famicom",
  "Wii",
  "BBC Microcomputer System",
  "Vectrex",
  "Microvision",
  "PDP-1",
  "PDP-11",
  "Microcomputer",
  "Game Boy Color",
  "Dreamcast",
  "ZX Spectrum",
  "Game Boy",
  "PC DOS",
  "PlayStation Portable",
  "Game Boy Advance",
  "Wii U",
  "N-Gage",
  "PC-8801",
  "VC 4000",
  "Turbografx-16/PC Engine CD",
  "Tatung Einstein",
  "Pokémon mini",
  "Sega 32X",
  "New Nintendo 3DS",
  "Nintendo 3DS",
  "SG-1000",
  "Nintendo Switch",
  "Donner Model 30",
  "Amazon Fire TV",
  "1292 Advanced Programmable Video System",
  "AY-3-8500",
  "FM-7",
  "Dragon 32/64",
  "Amstrad PCW",
  "Ferranti Nimrod Computer",
  "Windows Mixed Reality",
  "SDS Sigma 7",
  "CDC Cyber 70",
  "AY-3-8760",
  "Xbox One",
  "Sega CD",
  "Amiga",
  "Web browser",
  "Amiga CD32",
  "Acorn Archimedes",
  "Sega Mega Drive/Genesis",
  "AY-3-8603",
  "TRS-80 Color Computer",
  "PlayStation 5",
  "Nuon",
  "Sharp X1",
  "Neo Geo MVS",
  "Commodore 16",
  "Family Computer (FAMICOM)",
  "Analogue electronics",
  "EDSAC",
  "PDP-7",
  "HP 2100",
  "Call-A-Computer time-shared mainframe computer system",
  "PLATO",
  "Nintendo Entertainment System (NES)",
  "Sega Saturn",
  "Atari 2600",
  "Sega Master System",
  "Ouya",
  "OnLive Game System",
  "Philips CD-i",
  "Sharp X68000",
  "AY-3-8610",
  "NEC PC-6000 Series",
  "Oculus VR",
  "Nintendo GameCube",
  "Nintendo DS",
  "Atari Lynx",
  "Atari ST/STE",
  "BlackBerry OS",
  "TurboGrafx-16/PC Engine",
  "Imlac PDS-1"
];
